version: "3.8"

services:
  backend:
    image: ../backend
    platform: linux/amd64
    networks:
      - api.network
  
  frontend:
    image: ../frontend
    platform: linux/amd64
    networks:
      - api.network

networks:
  api.network:
