version: "3.8"

services:
  nginx:
    image: nginx:latest
    volumes:
      - /home/soranosuke/Secret_Santa_Project/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    ports:
      - '80:80'
    networks:
      - api.network

  backend:
    image: soranosuke/spp_backend:latest
    platform: linux/amd64
    networks:
      - api.network
  
  frontend:
    image: soranosuke/spp_frontend:latest
    platform: linux/amd64
    networks:
      - api.network

networks:
  api.network:
