version: "3.8"

services:
  backend:
    image: soranosuke/backend:latest
    platform: linux/amd64
    networks:
      - api.network
  
  frontend:
    image: soranosuke/frontend:latest
    platform: linux/amd64
    networks:
      - api.network

networks:
  api.network:
